version: '3.9'

services:
  tt-db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kronwinkl
      MYSQL_USER: kronwinkl
      MYSQL_PASSWORD: kronwinkl
