version: '3.9'

services:
  tt-db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kronwinkl
      MYSQL_USER: kronwinkl
      MYSQL_PASSWORD: kronwinkl
  myapp:
    image: myapp:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - 'DB_USER=kronwinkl'
      - 'DB_PASSWORD=kronwinkl'
      - 'DB_URL=jdbc:mariadb://host.docker.internal:3306/kronwinkl'
